dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: istio-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: ph-group-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: ph-istio-deployment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: ph-user-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.27
