dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: ph-auth-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: ph-group-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ph-invoice-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: ph-istio-deployment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ph-m3-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
- name: ph-payments-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: ph-user-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.125
