dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: ph-auth-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: ph-client-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.25
- name: ph-company-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: ph-esignature-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ph-group-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ph-invoice-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: ph-istio-deployment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ph-m3-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.62
- name: ph-member-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: ph-payments-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: ph-supplier-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: ph-user-service-serverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.128
